apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: three-tier
data:
  PORT: "5000"
  MONGODB_URI: "mongodb+srv://artisinghstp5313:Priyanshu123@cluster0.6aehyyw.mongodb.net/BlogVerse?appName=Cluster0"
  EMAIL_USER: "artisinghstp5313@gmail.com"
